### PR TITLE
Remove logging that shows in non-fusion pages as well

### PR DESCRIPTION
**Pull request by JackHowa**
Noticed this is showing up in the published version. Hope it's a small thing to build and redeploy 

shows up on all pages 

Screen Shot 2022-06-09 at 17 04 38

### CODE REVIEW

**Review by beltrancaliz — COMMENTED** [review]
I added this as it was really helpful for debugging, perhaps we can change this to be enabled in "dev mode" only?

**Comment by JackHowa** [comment]
huh interesting, yeah not sure how to allow-list that for debugging. Check for localhost domain?

**Comment by beltrancaliz** [comment]
> huh interesting, yeah not sure how to allow-list that for debugging. Check for localhost domain? if that, then a developer would see the log I guess for all of their localhost usage?

That would probably do for now. I pushed a commit with a check for the URL

**Review by JackHowa — COMMENTED** [review]
Yeah this looks like it's breaking on chrome.tabs ... huh. added this extension with load unpacked. then went to a github page, using chrome. Looks like content scripts can't use the tab api. 

`Additionally, content scripts cannot use tabs.query.` Feels kind of surprising.

https://developer.chrome.com/docs/extensions/reference/tabs/#get-the-current-tab

Screen Shot 2022-06-20 at 13 14 11

Maybe a compromise might be to comment out the code. Then a developer can uncomment it when they're using this locally?

**Pull request merged**
